import type { Metadata } from "next";

import Header from "@/app/(frontend)/components/Header/header";
import Footer from "@/app/(frontend)/components/Footer/footer";


import '@/app/(frontend)/scss/main.scss';
export const metadata: Metadata = {
  title: "Hodler Software",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Header />
        {children}
        {/*<Footer />*/}
      </body>
    </html>
  );
}
